[makl] a less horrible help for maklsh + some other cleanup

diff --git a/bin/maklsh.in b/bin/maklsh.in
--- a/bin/maklsh.in
+++ b/bin/maklsh.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: maklsh.in,v 1.4 2006/11/20 09:05:59 tho Exp $
+# $Id: maklsh.in,v 1.5 2006/11/20 18:29:37 tho Exp $
 
 export MAKL_DIR="@{{MAKL_ROOT}}"
 export MAKEFLAGS="-I ${MAKL_DIR}/mk"
@@ -33,9 +33,13 @@ search_cf_script ()
 
 display_help ()
 {
-    echo "MaKL version ${MAKL_VERSION}, (c) 2005-2006 Koanlogic srl"
-    echo "This is free software released under the BSD license."
-    echo "...help me..."
+    echo "MaKL version ${MAKL_VERSION}, (c) 2005-2006 Koanlogic srl         "
+    echo "This is free software released under the BSD license.             "
+    echo "                                                                  "
+    echo "Available tools are:                                              "
+    echo "makl      => GNU make wrapper                                     "
+    echo "maklconf  => configure script wrapper                             "
+    echo "maklhelp  => display this help                                    "
     exit 0
 }
 
@@ -49,18 +53,23 @@ CF_SCRIPTS="${MAKL_CF_SCRIPTS} ${CF_SCRIPTS}"
 case `basename $0`
 in
     makl)
+        # exec GNU make with user supplied arguments
         ${PATH_GNUMAKE} $@
         ;;
     maklconf)
         search_cf_script
+        # exec the selected configure script with user supplied arguments
         ${PATH_CF_SCRIPT} $@ 
         ;;
     maklhelp)
         display_help
+        exit 0
         ;;
     *)
-        echo "call me as maklconf or makl"
+        echo "don't call me directly, instead call me as makl or maklconf"
+        exit 1
         ;;
 esac
 
-exit 0
+# should not reach here; in case return a bad exit code
+exit 1
