cf: search for libs in usr/local:/usr by default

diff --git a/cf/makl_args_handle b/cf/makl_args_handle
--- a/cf/makl_args_handle
+++ b/cf/makl_args_handle
@@ -1,11 +1,12 @@
 #
-# $Id: makl_args_handle,v 1.9 2005/08/09 10:25:31 stewy Exp $
+# $Id: makl_args_handle,v 1.10 2005/08/30 18:08:04 stewy Exp $
 #
 
 
 # _makl_help
 #
-#   Print out the help menu 
+#   Print out the help menu.
+#   No return value.
 # 
 _makl_help () 
 {
@@ -29,6 +30,7 @@ _makl_help ()
 # _makl_help_opts
 #
 #   Print out the options.
+#   No return value.
 #
 _makl_help_opts() 
 {
@@ -65,6 +67,7 @@ _makl_help_opts()
 # _makl_noclean
 # 
 #   Don't clean cache at end of execution.
+#   No return value.
 #   
 _makl_noclean ()
 {
@@ -77,6 +80,7 @@ _makl_noclean ()
 #
 #   Set the base installation directory to pfx.
 #   $2 <must be empty>
+#   No return value.
 #
 _makl_prefix ()
 {
@@ -91,6 +95,7 @@ _makl_prefix ()
 #   Set directory for specific data type.
 #   $1 - directory type
 #   $2 - directory path
+#   No return value.
 #
 _makl_dir ()
 {
@@ -109,6 +114,7 @@ _makl_dir ()
 #
 #   Print content of a group of variables for debugging purposes.
 #   $1 - variable type
+#   No return value.
 #
 _makl_print ()
 {
@@ -137,10 +143,11 @@ _makl_print ()
     }
 }
 
-# makl_feature_c wrapper
+# _makl_feat_c id f
 #
-# $1 feature id
-# $2 file to be compiled
+#   $1 - feature id
+#   $2 - file to be compiled
+#   No return value.
 #
 _makl_feat_c ()
 {
@@ -155,10 +162,11 @@ _makl_feat_c ()
     [ $? = 0 ] || makl_err 2 "_makl_feat_c: feature $1 - failed to compile $2" 
 }
 
-# makl_feature_x wrapper
+# _makl_feat_x id f
 # 
 #   $1 - feature id 
 #   $2 - file to be executed
+#   No return value.
 #
 _makl_feat_x ()
 {
@@ -170,42 +178,45 @@ _makl_feat_x ()
     [ $? = 0 ] || makl_err 2 "makl_feat_x: feature $1 - failed to execute $2"
 }
 
-# makl_libdep wrapper
+# _makl_lib id val
 #
 #   $1 - library id
-#   $2 - value="<base_dir>:[<tst_file>]"
+#   $2 - value=<base_dir>
+#   0 on success, 1 on argument error, 2 on missing test file, 
+#   3 on unsuccessful compilation.
 #
 _makl_lib ()
 {
     [ $1 ] || _makl_args_err "makl_lib: missing package name!"
     [ $2 ] || _makl_args_err "makl_lib: requires value argument!"
 
-    id=$1
-    base=`echo $2 | cut -f1 -d":"`
-    tst=`echo $2 | cut -s -f2 -d":"`
-    
-    if [ ${tst} ]; then
-        [ -r ${tst} ] || makl_err 2 "makl_lib: unreadable test file (${tst})!" 
-    else
-        # try default test file
+    # check for inline code
+    tst=${makl_run_dir}/lib_testcode_$1.c
+    if [ ! -r ${tst} ]; then
         tst=`pwd`/build/lib$1.c
-        [ -r ${tst} ] || makl_err 2 "makl_lib: no test file for $1 (${tst})!" 
-    fi
 
-    makl_libdep ${id} ${base} ${tst}
+        if [ ! -r ${tst} ]; then
+            makl_warn "makl_lib: no test file for $1 (${tst})!" 
+            return 2
+        fi
+    fi
+    
+    makl_libdep $1 $2 ${tst}
 
     # add to list of found libs
     if [ $? = 0 ]; then
-       makl_req_found "lib" ${id}
+        makl_req_found "lib" $1
+        return 0
+    else
+        return 3
     fi
-
-    return $?
 }
 
-# _makl_args_err
+# _makl_args_err msg
 # 
 #   Print error message followed by usage.
 #   $1 - message
+#   No return value.
 #
 _makl_args_err ()
 {
@@ -214,10 +225,11 @@ _makl_args_err ()
     makl_err 1 $1
 }
 
-# _makl_args_handle 
+# _makl_args_handle arg
 #
 #   Handle an argument.
 #   $1 - argument to handle
+#   No return value.
 #
 _makl_arg_handle ()
 {
@@ -226,13 +238,14 @@ _makl_arg_handle ()
     val=`echo $1 | cut -s -f2 -d"="`
 
     _makl_${cmd} ${id} "${val}"
-    [ $? = 0 ] || _makl_args_err "Undefined command: '${cmd}'!"
+    [ $? = 0 ] || _makl_args_err "Failed command: '${cmd}'!"
 }
 
-# makl_args_handle
+# makl_args_handle args ...
 # 
 #   Process the configure command-line arguments.
 #   "$@" - command line arguments 
+#   No return value.
 #
 makl_args_handle()
 {
diff --git a/cf/makl_deps b/cf/makl_deps
--- a/cf/makl_deps
+++ b/cf/makl_deps
@@ -1,9 +1,9 @@
 #
-# $Id: makl_deps,v 1.4 2005/08/09 10:25:31 stewy Exp $
+# $Id: makl_deps,v 1.5 2005/08/30 18:08:04 stewy Exp $
 #
 
 
-# makl_require type id
+# makl_require type id dft
 #   
 #   Add a required dependency 
 #   $1 - dependency type
@@ -24,7 +24,7 @@ makl_require ()
     makl_args_add $1 $2 "$3" "<*>" ""
 }
 
-# makl_optional type id
+# makl_optional type id dft
 #   
 #   Add an optional dependency
 #   $1 - dependency type
@@ -62,9 +62,35 @@ makl_req_found ()
     echo $2 >> ${file}
 }
 
+# _makl_require_lib_def
+#   
+#   Search for required lib in default dirs.
+#   $1 - required lib  
+#   0 on success, 1 on lib not found.
+#
+_makl_require_lib_def ()
+{
+    file=${makl_run_dir}/args
+    
+    str=`makl_tab_get ${file} "lib" 3`
+    val=`makl_tab_var "${str}" "BASE"` 
+    dirs=`echo ${val} | sed 's/:/ /'`
+
+    for dir in ${dirs}; do
+        _makl_lib $1 ${dir}
+        if [ $? = 0 ]; then 
+            return 0
+        else
+            makl_dbg "Failed $1 compilation in ${dir}"
+        fi
+    done 
+
+    return 1
+}
+
 # _makl_require_check type
 #   
-#   Check that "type" dependencies have been fulfilled
+#   Check that "type" dependencies have been fulfilled.
 #   $1 - dependency type
 #   
 _makl_require_check ()
@@ -72,23 +98,18 @@ _makl_require_check ()
     f_req=${makl_run_dir}/deps_$1.require
     f_have=${makl_run_dir}/deps_$1.found
 
-    rm -f ${makl_run_dir}/err
-
     if [ ! -r ${f_req} ]; then
         return 0
     fi
-
     if [ ! -r ${f_have} ]; then
-        deps=`cat ${f_req}`
-        echo "Required $1 not found:"
-        echo ${deps}
-        makl_err 3 "Unfulfilled dependency!" 
+        touch ${f_have}
     fi
-    
-    # check that ${f_req} is subset of ${f_have}
+
+    rm -f ${makl_run_dir}/err
+
     cat ${f_req} | {
         while read req; do
-            cat ${f_have} | {
+            cat ${f_have} 2>/dev/null | {
                 found=0
                 while read have; do
                     if [ ${have} = ${req} ]; then
@@ -96,15 +117,45 @@ _makl_require_check ()
                     fi
                 done
                 if [ ${found} = 0 ]; then
-                    echo "Required $1 not found: ${req}"
-                    touch ${makl_run_dir}/err
-                    break
+                    # look in default directories before panic
+                    makl_dbg "searching for '$1${req}' in default paths" 
+                    case $1 in
+                        lib)
+                            _makl_require_lib_def ${req}
+                            ;;
+                        *) 
+                            ;;
+                    esac
+                    if [ ! $? = 0 ]; then
+                        echo "Required $1 not found: ${req}"
+                        touch ${makl_run_dir}/err
+                        break
+                    fi
                 fi
             }
         done
     }
-    
+   
     if [ -r ${makl_run_dir}/err ]; then
-        makl_err 3 "Unfulfilled dependency!"
+        makl_err 3 "unfulfilled dependency!"
     fi  
+}
+
+# makl_lib_testcode id
+#
+#   Set the test code for library id. Data is read from standard
+#   input.
+#   $1  - library id
+#   No return value.
+#
+makl_lib_testcode ()
+{
+    file=${makl_run_dir}/lib_testcode_$1.c
+
+    # create a clean file
+    [ -r ${file} ] && rm -f ${file}
+
+    while read line; do
+        echo ${line} >> ${file}
+    done
 }
