work in progress (added lib dependency)

diff --git a/cf/makl_utils b/cf/makl_utils
--- a/cf/makl_utils
+++ b/cf/makl_utils
@@ -63,3 +63,39 @@ makl_upper ()
 {
    echo $* | tr [a-z] [A-Z]
 }
+
+# makl_cleanup_rundir
+#
+#   Remove ${makl_run_dir}
+#   No return value.
+#
+makl_cleanup_rundir ()
+{
+    makl_yesno "do you want to remove ${makl_run_dir} ?" || return
+    rm -rf ${makl_run_dir}
+}
+
+# makl_yesno question
+#
+#   Present 'question' at terminal and wait the user to answer.
+#   $1 - question string
+#   Return '0' if [yY] was typed, '1' if [nN].
+makl_yesno ()
+{
+    echo -n "$1 " 
+    
+    while [ /bin/true ]; do 
+        read answer
+        case ${answer} in
+            [Yy])
+                return 0
+                ;;
+            [nN])
+                return 1
+                ;;
+            *)
+                echo -n "please say [yY] or [nN]: "
+                ;;
+        esac
+    done
+}
